name: Deploy to Vast.ai

on:
  push:
    branches:
      - zett-dev  # Chạy khi có thay đổi trên nhánh `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4
  

